### ISSUE TITLE
How to write a multi_sz type value into Registry.

### ISSUE THREAD

**Issue by yazi1297** [neo3587/regedit#1]
I just find your project, and I think it's awesome. Bud when I test your project, I found that I Can't write a multi_sz type value in registry. My code is 
`
reg.values["DependOnService"].write<neo::regedit::type::multi_sz>(L"multi_sz");
`
But the compiler told me that

error C2672: 'neo::regedit::value::write': no matching overloaded function found
error C2783: 'void neo::regedit::value::write(const std::string &)': could not deduce template argument for '<unnamed-symbol>'
note: see declaration of 'neo::regedit::value::write'
error C2780: 'void neo::regedit::value::write(void)': expects 0 arguments - 1 provided
note: see declaration of 'neo::regedit::value::write'

I don't know how to fix this problem.
So, I want to ask How to write a multi_sz type value into registry.

**Comment by neo3587** [comment]
That's cause it doesn't support unicode strings (guess I'll have to update it), also multi_sz expects 2 iterators cause it's intended for storing multiple string: 
```
std::vector<std::string> vec = { "multi_sz" };
reg.values["DependOnService"].write<neo::regedit::type::multi_sz>(vec.begin(), vec.end());
```
if you just want to store a single string, then you should use a `sz` instead, which... also doesn't support unicode strings (another thing to update), luckily converting strings is pretty easy:
```
std::string to_ascii(const std::wstring& wstr) {
    return std::string(wstr.begin(), wstr.end());
}
```

**Comment by neo3587** [comment]
well, just added unicode write support for `sz`, `expand_sz` and `multi_sz`, but remember that `multi_sz` stills using 2 iterators as parameters
